class discoverability {
    static aspect_metadata = {
        'field': [
            'label',
            'type',
            'default',
            'source_type',
            'source_default',
            'nullable',
            'description',
            'constraint',
            'accessor',
            'reference_to',
            'primary_accessor',
        ],
        'quality': [
            'label',
            'description',
            'keywords',
            'children',
            'related',
            'type',
            'state',
        ],
        'state': [
            'label',
            'description',
            'values',
            'initial',
            'final',
            'transitions',
            'transitions_from',
            'transitions_to',
        ],
        'quantity': [
            'label',
            'description',
            'values',
            'ranges',
            'units',
            'unit_labels',
            'min',
            'max',
            'step',
            'precision',
        ],
        'operation': [
            'method',
            'parameters',
            'accepts',
            'provides',
            'requires',
            'errors',
            'signature',
            'description',
            'is_create',
            'is_read',
            'is_update',
            'is_delete',
            'is_list',
            'is_search',
            'is_action',
            'is_function',
        ],
        'map': [
            'type',
            'label',
            'tag',
            'version',
            'last_modified',
            'description',
            'from',
            'to',
            'known_callers',
            'previous',
            'map',
        ],
        'authorization': [
            'label',
            'description',
            'realms',
            'roles',
            'permissions',
            'degree',
            'read',
            'write',
            'update',
            'delete',
            'create',
            'list',
            'search',
            'action',
            'admin',
            'browse',
        ]
    }

    discover(resource: string | null | Resource = null){

    }
}
